$content = [System.IO.File]::ReadAllText("index.html")
$content = $content.Replace("Â·", "·")
$content = $content.Replace("â€”", " — ")
$content = $content.Replace("â€“", "–")
$content = $content.Replace("ðŸŽ“", "🎓")
$content = $content.Replace("ðŸ“ˆ", "📈")
$content = $content.Replace("ðŸ“š", "📚")
$content = $content.Replace("ðŸ¤", "🤝")
$content = $content.Replace("â€", '"')
[System.IO.File]::WriteAllText("index.html", $content, [System.Text.Encoding]::UTF8)
